Removes all legacy python/system compatibility userdata

diff --git a/modules/guac/ra_guac_autoscale_public_alb.template.cfn.yaml b/modules/guac/ra_guac_autoscale_public_alb.template.cfn.yaml
--- a/modules/guac/ra_guac_autoscale_public_alb.template.cfn.yaml
+++ b/modules/guac/ra_guac_autoscale_public_alb.template.cfn.yaml
@@ -643,46 +643,19 @@ Resources:
           #!/bin/bash -xe
           # CFN LaunchConfig Update Toggle: ${ForceUpdateToggle}
 
-          # Get pip
-          curl --silent --show-error --retry 5 -L https://bootstrap.pypa.io/get-pip.py | python
-
-          # Add pip to path
-          hash pip 2> /dev/null || PATH="${!PATH}:/usr/local/bin"
-
-          # Upgrade setuptools
-          pip install --upgrade setuptools
-
-          # Fix python urllib3 warnings
-          yum -y install gcc python-devel libffi-devel openssl-devel
-          pip install pyopenssl ndg-httpsclient pyasn1
-
-          # Get cfn utils
-          pip install https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-latest.tar.gz
-
-          # Remove gcc now that it is no longer needed
-          yum -y remove gcc --setopt=clean_requirements_on_remove=1
-
-          # Fixup cfn utils
-          INITDIR=$(find -L /opt/aws/apitools/cfn-init/init -name redhat 2> /dev/null || echo /usr/init/redhat)
-          chmod 775 ${!INITDIR}/cfn-hup
-          ln -f -s ${!INITDIR}/cfn-hup /etc/rc.d/init.d/cfn-hup
-          chkconfig --add cfn-hup
-          chkconfig cfn-hup on
-          mkdir -p /opt/aws/bin
-          BINDIR=$(find -L /opt/aws/apitools/cfn-init -name bin 2> /dev/null || echo /usr/bin)
-          for SCRIPT in cfn-elect-cmd-leader cfn-get-metadata cfn-hup cfn-init cfn-send-cmd-event cfn-send-cmd-result cfn-signal
-          do
-            ln -s ${!BINDIR}/${!SCRIPT} /opt/aws/bin/${!SCRIPT} 2> /dev/null || echo Skipped symbolic link, /opt/aws/bin/${!SCRIPT} already exists
-          done
+          # Install ssm agent
+          yum -y install https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/linux_amd64/amazon-ssm-agent.rpm || true
 
           # Add cfn utils to path
           hash cfn-signal 2> /dev/null || PATH="${!PATH}:/usr/local/bin:/opt/aws/bin"
 
-          # Install ssm agent
-          yum -y install https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/linux_amd64/amazon-ssm-agent.rpm || true
-
           # Execute cfn-init
-          /opt/aws/bin/cfn-init -v -c config --stack ${AWS::StackName} --resource LaunchConfig --region ${AWS::Region} || (echo 'ERROR: cfn-init failed! Aborting!'; /opt/aws/bin/cfn-signal -e 1 --stack ${AWS::StackName} --resource AutoScalingGroup --region ${AWS::Region}; exit 1)
+          cfn-init -v -c config --stack ${AWS::StackName} --resource LaunchConfig --region ${AWS::Region} || \
+            ( \
+            echo 'ERROR: cfn-init failed! Aborting!' ; \
+            cfn-signal -e 1 --stack ${AWS::StackName} --resource AutoScalingGroup --region ${AWS::Region} ; \
+            exit 1 ; \
+            )
     Type: AWS::AutoScaling::LaunchConfiguration
   Listener:
     Properties:
